#ifndef EJERCICIOS_H
#define EJERCICIOS_H
int Ejercicio1();
int Ejercicio2();
int Ejercicio3();
int Ejercicio4();
int Ejercicio5();
int Ejercicio6();
int Ejercicio7();
int Ejercicio8();	
int	Ejercicio9();
int Ejercicio10();
int Ejercicio11();
int Ejercicio12();
int Ejercicio13();
int Ejercicio14();
int Ejercicio15();
int Ejercicio16();
int Ejercicio17();
int Ejercicio18();
int Ejercicio19();
int Ejercicio20();
#endif